version: '2'

services:
  configservice:
    image: flyceek/apollo:alpine-apollo-configservice-v1.4
    ports:
      - 18086:8080
    restart: always
    environment:
      - JAVA_OPTS=-Dspring.datasource.url=jdbc:mysql://10.28.19.196:3306/ApolloConfigDB?characterEncoding=utf8 -Dspring.datasource.username=root -Dspring.datasource.password=123321 -Deureka.instance.ip-address=10.28.19.196 -Deureka.instance.nonSecurePort=18086 -Deureka.instance.instance-id=10.28.19.196:apollo-conf-test:18086 -Deureka.server.enable-self-preservation=true -Deureka.instance.hostname=10.28.19.196 -Deureka.client.serviceUrl.defaultZone=http://10.28.19.196:18086
    mem_limit: 256m
  adminservice:
    image: flyceek/apollo:alpine-apollo-adminservice-v1.4
    ports:
      - 18096:8090
    restart: always
    environment:
      JAVA_OPTS: -Dspring.datasource.url=jdbc:mysql://10.28.19.196:3306/ApolloConfigDB?characterEncoding=utf8 -Dspring.datasource.username=root -Dspring.datasource.password=123321 -Deureka.instance.ip-address=10.28.19.196 -Deureka.instance.nonSecurePort=18096 -Deureka.instance.instance-id=10.28.19.196:apollo-admin-test:18096 -Deureka.instance.hostname=10.28.19.196 -Deureka.client.serviceUrl.defaultZone=http://10.28.19.196:18086
    mem_limit: 256m