version: '3.1'

services:
  configservice:
    image: flyceek/apollo:alpine-apollo-configservice-v1.4
    ports:
      - 18086:8080
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://10.28.19.196:18336/ApolloPortalDB?characterEncoding=utf8
      spring.datasource.username: root
      spring.datasource.password: 123321
      eureka.instance.ip-address: 10.28.19.196
      eureka.instance.non-secure-port: 18086
      eureka.instance.instance-id: 10.28.19.196:apollo-conf-test:18086
      eureka.instance.hostname: 10.28.19.196
      eureka.client.service-url.default_zone: http://10.28.19.196:18086
      eureka.server.enable-self-preservation: true
  adminservice:
    image: flyceek/apollo:alpine-apollo-adminservice-v1.4
    ports:
      - 18096:8090
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://10.28.19.196:18336/ApolloPortalDB?characterEncoding=utf8
      spring.datasource.username: root
      spring.datasource.password: 123321
      eureka.instance.ip-address: 10.28.19.196
      eureka.instance.non-secure-port: 18096
      eureka.instance.hostname: 10.28.19.196
      eureka.instance.instance-id: 10.28.19.196:apollo-admin-test:18096
      eureka.client.service-url.default-zone: http://10.28.19.196:18086