version: '3.1'

services:
  portal:
    image: flyceek/apollo:alpine-apollo-portal-v1.4
    ports:
      - 18076:8070
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://10.28.19.196:18336/ApolloConfigDB?characterEncoding=utf8
      - spring.datasource.username=root
      - spring.datasource.password=123321
      - spring.profiles.active=ldap
      - meta.servers=dev.meta=http://10.28.19.196:18086,http://10.4.99.4:18086
      - IFS=;
    extra_hosts:
      ldap.centaline.com.cn: 10.4.19.13
    volumes:
      - ./application-ldap.yml:/opt/apollo/apollo-portal-v1.4.0/config/application-ldap.yml
