version: '3'
services:
  apollo-portal:
    image: flyceek/apollo:alpine-apollo-portal-v1.4
    container_name: apollo-portal
    network_mode: "host"
    ports:
      - 18076:8070
    environment:
      SERVER_PORT: 8070
      DS_URL: "jdbc:mysql://10.28.19.196:18336/ApolloPortalDB?characterEncoding=utf8"
      DS_USERNAME: "root"
      DS_PASSWORD: "123321"
      DEV_META: "http://10.28.19.196:18086,http://10.4.99.4:18086"
      FAT_META: ""
      UAT_META: ""
      LPT_META: ""
      PRO_META: ""
    # depends_on:
    #   - apollo-adminservice
    extra_hosts:
      ldap.centaline.com.cn: 10.4.19.13
    volumes:
      - ./application-ldap.yml:/opt/apollo/apollo-portal-v1.4.0/config/application-ldap.yml
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"