version: '2'

services:
  phantomjs:
    image: 'flyceek/pyspider:latest'
    command: phantomjs
    cpu_shares: 256    
    environment:
      - 'EXCLUDE_PORTS=5000,23333,24444'
    expose:
      - '25555'
    mem_limit: 256m
    restart: always

  phantomjs-lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - phantomjs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always

  fetcher:
    image: 'flyceek/pyspider:latest'
    command: '--message-queue "amqp://flyceek:123321@10.28.19.196:5672/%2F" --phantomjs-proxy "phantomjs:80" fetcher --xmlrpc'
    cpu_shares: 256   
    environment:
      - 'EXCLUDE_PORTS=5000,23333,25555'
    links:
      - 'phantomjs-lb:phantomjs'
    mem_limit: 256m
    restart: always

  fetcher-lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - fetcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  processor:
    image: 'flyceek/pyspider:latest'
    command: '--projectdb "mongodb+projectdb://flyceek:123321@10.28.19.196:27017/projectdb?authSource=admin" --message-queue "amqp://flyceek:123321@10.28.19.196:5672/%2F" processor'
    cpu_shares: 256
    mem_limit: 256m
    restart: always

  result_worker:
    image: 'flyceek/pyspider:latest'
    command: '--taskdb "mongodb+taskdb://flyceek:123321@10.28.19.196:27017/taskdb?authSource=admin"  --projectdb "mongodb+projectdb://flyceek:123321@10.28.19.196:27017/projectdb?authSource=admin" --resultdb "mongodb+resultdb://flyceek:123321@10.28.19.196:27017/resultdb?authSource=admin" --message-queue "amqp://flyceek:123321@10.28.19.196:5672/%2F" result_worker'
    cpu_shares: 256
    mem_limit: 256m
    restart: always

networks:
  default:
    external:
      name: pyspider


