version: '3.1'

services:
  percona-mysql:
    image: percona
    restart: always
    ports:
      - 18333:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123321
      # MYSQL_USER: paranora
      # MYSQL_PASSWORD: 123456
      MYSQL_INITDB_SKIP_TZINFO: Asia/Shanghai

  percona-adminer:
    image: adminer
    restart: always
    ports:
      - 18181:8080