version: "2"

services:
  nexus:
    image: 'flyceek/centosu-nexus:nexus3'
    restart: always
    container_name: "nexus3"
    # extra_hosts:
    #   - "redis.centaline.com:10.4.19.105"
    # expose:
    #   - "8029"
    environment:
      -"NEXUS_IP_ADDRESS=10.28.11.199"
    ports:
      - "8081:8081"
      - "8443:8443"
      - "8442:8442"
    logging:
      options:
      max-size: 50m
    mem_limit: 2048M
    volumes:
      - "/var/nexus-data:/var/nexus-data"