version: "2"

services:
  jenkins:
    image: 'flyceek/alpine-jenkins:latest'
    restart: always
    container_name: "jenkins"
    expose:
      - "8029"
    ports:
      - "8029:8080"
    volumes:
      - "/var/jenkins:/var/jenkins"