version: "3.3"
services:
  mongodb:
    image: mongo:4
    volumes:
      - type: bind
        source: /var/yapi/mongo/data/db
        target: /data/db
    ports:
      - 8081:8081
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sh.34211
  yapi-web:
    image: flyceek/ubuntu-yapi:1.3.17
    command: /bin/bash -c "[ ! -e /opt/soft/yapi/yapi-v1.3.17/log/init.lock ] && npm run install-server && touch /opt/soft/yapi/yapi-v1.3.17/log/init.lock; npm run start"
    links:
      - mongodb:mongodb
    ports:
      - 3003:3000
    volumes:
      - type: bind
        source: /var/yapi/config.json
        target: /opt/soft/yapi/config.json
      - type: bind
        source: /var/yapi/log
        target: /opt/soft/yapi/yapi-v1.3.17/log