version: "3.3"
services:
  yapi-mongodb:
    image: mongo:4
    volumes:
      - type: bind
        source: /var/yapi/mongo/data/db
        target: /data/db
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: sh.34211
  yapi-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: yapi-mongodb
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: sh.34211
  yapi-web:
    image: flyceek/ubuntu-yapi:1.3.17
    command: /bin/bash -c "[ ! -e /opt/soft/yapi/yapi-v1.3.17/log/init.lock ] && npm install && npm run install-server && touch /opt/soft/yapi/yapi-v1.3.17/log/init.lock; npm run start"
    links:
      - yapi-mongodb:mongodb
    ports:
      - 3003:3000
    volumes:
      - type: bind
        source: /var/yapi/config.json
        target: /opt/soft/yapi/config.json
      - type: bind
        source: /var/yapi/log
        target: /opt/soft/yapi/yapi-v1.3.17/log