
spring:
  ldap:
    base: "OU=中原地产,DC=centaline,DC=com,DC=cn"
    username: "ldapshdev@centaline.com.cn" # 配置管理员账号，用于搜索、匹配用户
    password: "123321"
    searchFilter: "(sAMAccountName={0})"  # 用户过滤器，登录的时候用这个过滤器来搜索用户
    urls:
    - "ldap://10.4.19.13:389"

ldap:
  mapping: # 配置 ldap 属性
    objectClass: "user" # ldap 用户 objectClass 配置
    loginId: "sAMAccountName" # ldap 用户惟一 id，用来作为登录的 id
    userDisplayName: "cn" # ldap 用户名，用来作为显示名
    email: "userPrincipalName" # ldap 邮箱属性
  filter: # 可选项，配置过滤，目前只支持 memberOf
    memberOf: "OU=中原地产,DC=centaline,DC=com,DC=cn" # 只允许 memberOf 属性为 ServiceDEV 和 WebDEV 的用户访问